safe: true
lsi: false
highlighter: rouge

exclude: ['README.md', 'config.rb', '*.sln', '*.suo', '*.config']

domain: accord-framework.net
title: Accord.NET Machine Learning Framework


gems:
  - jekyll-sitemap

google_analytics:
  account: UA-3114672-6

github:
  username: cesarsouza

disqus:
  id: accord-net

framework:
  version: v3.6
  download-installer: https://www.nuget.org/packages?q=accord.net
  download-archive:   https://github.com/accord-net/framework/releases/download/v3.5.0/Accord.NET-3.6.0-archive.rar
  
