safe: true
lsi: false
highlighter: rouge
repository: accord-net/accord-net.github.io

exclude: ['README.md', 'config.rb', '*.sln', '*.suo', '*.config']
#exclude: ['README.md', 'config.rb', '*.sln', '*.suo', '*.config', 'docs']

domain: accord-framework.net
title: Accord.NET Machine Learning Framework


plugins:
  - jekyll-sitemap


google_analytics:
  account: UA-3114672-6

github:
  username: cesarsouza

disqus:
  id: accord-net

framework:
  version: v3.7
  download-installer: https://www.nuget.org/packages?q=accord.net
  download-archive:   https://github.com/accord-net/framework/releases/download/v3.7.0/Accord.NET-3.7.0-archive.rar
  
